name: build site

# on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2

      - name: use node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: install and build 🔧
        run: |
          npm install -g gatsby-cli
          npm ci
          npm run fetch:openapi
          npx gatsby build

      - name: test 🧪
        run: npm run test:coverage

      - name: deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: public
