name: build site

# on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2

      - name: use node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: install and build 🔧
        run: |
          npm ci --legacy-peer-deps
          npm run fetch:openapi
          npm run build

      - name: test 🧪
        run: npm run test:coverage

      - name: deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
